# Generated by Django 4.1 on 2023-04-14 03:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, verbose_name="STT")),
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="Mã đất nước"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Tên đất nước"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Đất nước",
                "db_table": "tb_country",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="history_commune",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("id", models.CharField(max_length=200, verbose_name="id")),
                (
                    "time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Thời gian"),
                ),
                (
                    "info",
                    models.JSONField(default={}, verbose_name="Thông tin chỉnh sửa"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        null=True, srid=4326, verbose_name="Bản đồ"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Lịch sử chỉnh sửa xã - phường - thị trấn",
                "db_table": "tb_history_commune",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="history_district",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("id", models.CharField(max_length=200, verbose_name="id")),
                (
                    "time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Thời gian"),
                ),
                (
                    "info",
                    models.JSONField(default={}, verbose_name="Thông tin chỉnh sửa"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        null=True, srid=4326, verbose_name="Bản đồ"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Lịch sử chỉnh sửa quận - huyện",
                "db_table": "tb_history_district",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="history_province",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("id", models.CharField(max_length=200, verbose_name="id")),
                (
                    "time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Thời gian"),
                ),
                (
                    "info",
                    models.JSONField(default={}, verbose_name="Thông tin chỉnh sửa"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        null=True, srid=4326, verbose_name="Bản đồ"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Lịch sử chỉnh sửa tỉnh - Thành phố",
                "db_table": "tb_history_province",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, verbose_name="STT")),
                (
                    "id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Mã tỉnh",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Tên tỉnh")),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        null=True, srid=4326, verbose_name="Bản đồ"
                    ),
                ),
                (
                    "id_parent",
                    models.ForeignKey(
                        db_column="id_country",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_boundary.country",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tỉnh - Thành phố",
                "db_table": "tb_province",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, verbose_name="STT")),
                (
                    "id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Mã huyện",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Tên huyện")),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        null=True, srid=4326, verbose_name="Bản đồ"
                    ),
                ),
                (
                    "id_parent",
                    models.ForeignKey(
                        db_column="id_province",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_boundary.province",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quận - Huyện - Thị xã ",
                "db_table": "tb_district",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Commune",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, verbose_name="STT")),
                (
                    "id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Mã xã",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Tên xã")),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        null=True, srid=4326, verbose_name="Bản đồ"
                    ),
                ),
                (
                    "id_parent",
                    models.ForeignKey(
                        db_column="id_district",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_boundary.district",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Xã/ Phường/ Thị trấn",
                "db_table": "tb_commune",
                "ordering": ["id"],
            },
        ),
    ]
