# Generated by Django 3.2.15 on 2023-05-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boundary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='district',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='province',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
